### ISSUE TITLE
Add a collection of video cover images

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/artifacts#16]
[This](https://github.com/kottans/frontend/issues/276) task may require images to create links for a somewhat better UX.

Suggested locations within this repo structure:
- `youtube/cover_images/frontend/2019/`
- `youtube/cover_images/frontend/2018/`
- `youtube/cover_images/frontend/p2p/` or `youtube/cover_images/p2p/`

**Comment by yevhenorlov** [comment]
titles with corresponding image urls are available [here](https://github.com/kottans/frontend/issues/276#issuecomment-530913090).

**Comment by OleksiyRudenko** [comment]
Closing this issue for it's been agreed we do not want this kind of media in this repo
